### ISSUE TITLE
AND condition are not working as expected

### ISSUE THREAD

**Issue by ihotz** [ansible-lockdown/RHEL7-CIS-Audit#11]
If first condition is true and second condition is false, result is true and code block will be executed:
`{{ if ((.Vars.rhel7cis_config_aide) and .Vars.rhel7cis_level1) }}`

I did not found a working solution (braces on different possitions), so I implemented a simple workaround with just multiple if conditions:
```
{{ if .Vars.rhel7cis_config_aide }}
{{ if .Vars.rhel7cis_level1 }}
```

**Comment by uk-bolly** [comment]
hi @ihotz 

Thanks for raising these issues, we are only able to test a few builds so all feedback is gratefully received where we may have missed options or configurations. I will work through these and add to the next release.

Many thanks once again

uk-bolly

**Comment by uk-bolly** [comment]
hi @ihotz 

Thank you for highlighting these improvements to the audit tasks.
As you may have seen there has been a few other PR's pulled in or slightly changed meaning that this one which was linked from your previous PR's may require to be rebased and updated.
We appreciate the work that you have done and if you would like to rebase and update the PR that would be excellent. We are also happy to pick this up along with other improvement plans we have if that works also.

Many thanks once again

uk-bolly

**Comment by uk-bolly** [comment]
Hi @ihotz 

Thank you once again for highlighting the issues and improvements that can be made. We have hopefully now addressed all the issues raised and the related PR's were pulled in a while ago.
To let you know we are also getting ready to release the latest cis benchmarks for rh7 and rh8. 

Best regards and thanks once again

uk-bolly
