### ISSUE TITLE
if conditions needs before related code block

### ISSUE THREAD

**Issue by ihotz** [ansible-lockdown/RHEL7-CIS-Audit#12]
When exluding a rule like 1.1.2, because I haven't a separate /tmp Partition, the Audit Playbook can't parse output, because "/tmp" mount is not found on system.
```
mount:
  /tmp:
  {{ if .Vars.rhel7cis_rule_1_1_2 }}
```

Solution: Move condition before command or code block:
```
mount:
  {{ if .Vars.rhel7cis_rule_1_1_2 }}
  /tmp:
```

multiple files are affected.

**Comment by uk-bolly** [comment]
hi @ihotz 

Thank you for highlighting these improvements to the audit tasks.
As you may have seen there has been a few other PR's pulled in or slightly changed meaning that this one which was linked from your previous PR's may require to be rebased and updated.
We appreciate the work that you have done and if you would like to rebase and update the PR that would be excellent. We are also happy to pick this up along with other improvement plans we have if that works also.

Many thanks once again

uk-bolly

**Comment by uk-bolly** [comment]
Hi @ihotz 

Thank you once again for highlighting the issues and improvements that can be made. We have hopefully now addressed all the issues raised and the related PR's were pulled in a while ago.
To let you know we are also getting ready to release the latest cis benchmarks for rh7 and rh8. 

Best regards and thanks once again

uk-bolly
