### ISSUE TITLE
Audit can only be run via ./run_audit.sh

### ISSUE THREAD

**Issue by db0** [ansible-lockdown/RHEL7-CIS-Audit#25]
Sorry if the question is invalid. It's my first time using goss and I'm trying to test using this repo

When running goss, it is claiming that I'm missing a variable

```
/usr/local/bin/goss --vars /tmp/CIS.yml -g RHEL7-CIS-Audit/goss.yml validate
Error: template: test:46:38: executing "test" at <.Vars.machine_uuid>: map has no entry for key "machine_uuid"
```

This is based on a pure clone of this repo and a copy of CIS.yml

Looking around, I noticed that `./run_audit.sh` is setting the requested variables, but this is not mentioned in the readme. 

Is this the expected way to use this repo?

I did experiment is setting the variables in the places expected by that script, but I'm having to read through the code to see what it expects so it's not ideal. 

**Expected Behavior**

The commands to use this repo mentioned in the readme should work

**Comment by uk-bolly** [comment]
Hi @db0 

Thank you for taking the time to ask the question. You are correct the best way is to run the audit via the script due to the embedded variables that are set, this is for those who are running over multiple servers to distinguish the different reports per server.
Taking your point on board, I have just pushed up a new branch (standalone) that should give you the options to do just that and i have updated the docs accordingly in the docs folder on how this can be done.
Please let me know how you get on with this branch and if this covers off your questions and requirements?

best regards

uk-bolly

**Comment by db0** [comment]
Cool beans. BTW If you have an ansible playbook which calls the ./run_audit.sh over multiple servers I would also be interested in checking it, as a reference

**Comment by uk-bolly** [comment]
Hi @db0 

Thank you again for the feedback, if that works as you expected? I will raise a PR to add that into the main branches.
With the regard to the Ansible playbook, hopefully the remediation repository https://github.com/ansible-lockdown/RHEL7-CIS there are some Ansible steps to assist in setting up goss on a host, import the repository and run the related run_audit.sh using variables supplied by the playbook itself. They work closely together so you are testing the same setting you are applying.
There should be some pieces that you could reuse there.

Best regards

uk-bolly

**Comment by uk-bolly** [comment]
This could be a good idea for an isolated capability (added to roadmap).
With regard to the remediation role, you could run it with a tag? run_audit and hopefully should run the script for you and set it up according to the variables you have set.

uk-bolly

**Comment by db0** [comment]
OK I'll check. I just converted your role into a collection and it seems to be working. so I'll try to pass the variables to that.

I'm planning to turn this role distro-agnostic for my infra. I'll let you know how it goes.

**Comment by uk-bolly** [comment]
hi @db0 

It should all be in place now and hopefully working for you as expected?

thanks again

uk-bolly
